project_name: junos-exporter

dist: artifacts
before:
   hooks:
     - go mod download
builds:
  - env:
    - CGO_ENABLED=0

nfpms:
  - homepage:  https://freedom.nl
    description: JunOS Exporter for Prometheus
    maintainer: Freedom Internet DevOps <systeembeheer@freedomnet.nl>
    license: MIT License
    vendor: Freedom Internet
    contents:
      - src: scripts/defaults
        dst: /etc/default/prometheus-junos-exporter
      - src: scripts/systemd/prometheus-junos-exporter.service
        dst: /usr/lib/systemd/system/prometheus-junos-exporter.service
    formats:
      - deb
      - rpm
    dependencies:
      - systemd
    scripts:
        postinstall: scripts/postinstall.sh

archives:
  - id: archive
    wrap_in_directory: true
    files:
      - README.md